//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.27 at 10:10:35 PM COT 
//


package ec.edu.espe.arqsoftware.prestamo.zamora_zuniga.ws;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ec.edu.espe.arqsoftware.prestamo.zamora_zuniga.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ec.edu.espe.arqsoftware.prestamo.zamora_zuniga.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ObtenerPrestamoIdRequest }
     * 
     */
    public ObtenerPrestamoIdRequest createObtenerPrestamoIdRequest() {
        return new ObtenerPrestamoIdRequest();
    }

    /**
     * Create an instance of {@link ObtenerPrestamoIdResponse }
     * 
     */
    public ObtenerPrestamoIdResponse createObtenerPrestamoIdResponse() {
        return new ObtenerPrestamoIdResponse();
    }

    /**
     * Create an instance of {@link CuotaPrestamoRS }
     * 
     */
    public CuotaPrestamoRS createCuotaPrestamoRS() {
        return new CuotaPrestamoRS();
    }

    /**
     * Create an instance of {@link ObtenerPrestamoIdYEstadoRequest }
     * 
     */
    public ObtenerPrestamoIdYEstadoRequest createObtenerPrestamoIdYEstadoRequest() {
        return new ObtenerPrestamoIdYEstadoRequest();
    }

    /**
     * Create an instance of {@link ObtenerPrestamoIdYEstadoResponse }
     * 
     */
    public ObtenerPrestamoIdYEstadoResponse createObtenerPrestamoIdYEstadoResponse() {
        return new ObtenerPrestamoIdYEstadoResponse();
    }

}
