//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.27 at 10:10:35 PM COT 
//


package ec.edu.espe.arqsoftware.prestamo.zamora_zuniga.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="codigoPrestamo" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "codigoPrestamo"
})
@XmlRootElement(name = "obtenerPrestamoIdRequest")
public class ObtenerPrestamoIdRequest {

    protected int codigoPrestamo;

    /**
     * Gets the value of the codigoPrestamo property.
     * 
     */
    public int getCodigoPrestamo() {
        return codigoPrestamo;
    }

    /**
     * Sets the value of the codigoPrestamo property.
     * 
     */
    public void setCodigoPrestamo(int value) {
        this.codigoPrestamo = value;
    }

}
