//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.27 at 10:10:35 PM COT 
//


package ec.edu.espe.arqsoftware.prestamo.zamora_zuniga.ws;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import lombok.Setter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cuotaPrestamoRS" type="{http://espe.edu.ec/arqsoftware/prestamo/zamora_zuniga/ws}cuotaPrestamoRS" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cuotaPrestamoRS"
})
@Setter
@XmlRootElement(name = "obtenerPrestamoIdYEstadoResponse")
public class ObtenerPrestamoIdYEstadoResponse {

    protected List<CuotaPrestamoRS> cuotaPrestamoRS;

    /**
     * Gets the value of the cuotaPrestamoRS property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cuotaPrestamoRS property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCuotaPrestamoRS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CuotaPrestamoRS }
     * 
     * 
     */
    public List<CuotaPrestamoRS> getCuotaPrestamoRS() {
        if (cuotaPrestamoRS == null) {
            cuotaPrestamoRS = new ArrayList<CuotaPrestamoRS>();
        }
        return this.cuotaPrestamoRS;
    }

}
