//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.27 at 10:10:35 PM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://espe.edu.ec/arqsoftware/prestamo/zamora_zuniga/ws", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ec.edu.espe.arqsoftware.prestamo.zamora_zuniga.ws;
