//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrearCliente
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://espe.edu.ec/arquisoft/cliente/ws", ConfigurationName="CrearCliente.ClientePort")]
    public interface ClientePort
    {
        
        // CODEGEN: Generating message contract since the operation getClienteById is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CrearCliente.getClienteByIdResponse1 getClienteById(CrearCliente.getClienteByIdRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CrearCliente.getClienteByIdResponse1> getClienteByIdAsync(CrearCliente.getClienteByIdRequest1 request);
        
        // CODEGEN: Generating message contract since the operation modificarEstadoClienteBancaWeb is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CrearCliente.modificarEstadoClienteBancaWebResponse1 modificarEstadoClienteBancaWeb(CrearCliente.modificarEstadoClienteBancaWebRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CrearCliente.modificarEstadoClienteBancaWebResponse1> modificarEstadoClienteBancaWebAsync(CrearCliente.modificarEstadoClienteBancaWebRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getCliente is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CrearCliente.getClienteResponse getCliente(CrearCliente.getClienteRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CrearCliente.getClienteResponse> getClienteAsync(CrearCliente.getClienteRequest1 request);
        
        // CODEGEN: Generating message contract since the operation eliminarCliente is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CrearCliente.eliminarClienteResponse1 eliminarCliente(CrearCliente.eliminarClienteRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CrearCliente.eliminarClienteResponse1> eliminarClienteAsync(CrearCliente.eliminarClienteRequest1 request);
        
        // CODEGEN: Generating message contract since the operation createdClienteReturnId is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CrearCliente.createdClienteReturnIdResponse1 createdClienteReturnId(CrearCliente.createdClienteReturnIdRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CrearCliente.createdClienteReturnIdResponse1> createdClienteReturnIdAsync(CrearCliente.createdClienteReturnIdRequest1 request);
        
        // CODEGEN: Generating message contract since the operation createdCliente is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CrearCliente.createdClienteResponse1 createdCliente(CrearCliente.createdClienteRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CrearCliente.createdClienteResponse1> createdClienteAsync(CrearCliente.createdClienteRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://espe.edu.ec/arquisoft/cliente/ws")]
    public partial class getClienteByIdRequest
    {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://espe.edu.ec/arquisoft/cliente/ws")]
    public partial class Cliente
    {
        
        private string idField;
        
        private string tipoIdentificacionField;
        
        private string identificacionField;
        
        private string apellidoPaternoField;
        
        private string apellidoMaternoField;
        
        private string nombre1Field;
        
        private string nombre2Field;
        
        private string provinciaField;
        
        private string cantonField;
        
        private string parroquiaField;
        
        private string direccionField;
        
        private string telefonoField;
        
        private string emailField;
        
        private System.DateTime fechaNaciemientoField;
        
        private string estadoCivilField;
        
        private string estadoBancaWebField;
        
        private string estadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string tipoIdentificacion
        {
            get
            {
                return this.tipoIdentificacionField;
            }
            set
            {
                this.tipoIdentificacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string identificacion
        {
            get
            {
                return this.identificacionField;
            }
            set
            {
                this.identificacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string apellidoPaterno
        {
            get
            {
                return this.apellidoPaternoField;
            }
            set
            {
                this.apellidoPaternoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string apellidoMaterno
        {
            get
            {
                return this.apellidoMaternoField;
            }
            set
            {
                this.apellidoMaternoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string nombre1
        {
            get
            {
                return this.nombre1Field;
            }
            set
            {
                this.nombre1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string nombre2
        {
            get
            {
                return this.nombre2Field;
            }
            set
            {
                this.nombre2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string provincia
        {
            get
            {
                return this.provinciaField;
            }
            set
            {
                this.provinciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string canton
        {
            get
            {
                return this.cantonField;
            }
            set
            {
                this.cantonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string parroquia
        {
            get
            {
                return this.parroquiaField;
            }
            set
            {
                this.parroquiaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string direccion
        {
            get
            {
                return this.direccionField;
            }
            set
            {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string telefono
        {
            get
            {
                return this.telefonoField;
            }
            set
            {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=13)]
        public System.DateTime fechaNaciemiento
        {
            get
            {
                return this.fechaNaciemientoField;
            }
            set
            {
                this.fechaNaciemientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string estadoCivil
        {
            get
            {
                return this.estadoCivilField;
            }
            set
            {
                this.estadoCivilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string estadoBancaWeb
        {
            get
            {
                return this.estadoBancaWebField;
            }
            set
            {
                this.estadoBancaWebField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://espe.edu.ec/arquisoft/cliente/ws")]
    public partial class getClienteByIdResponse
    {
        
        private Cliente clienteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Cliente Cliente
        {
            get
            {
                return this.clienteField;
            }
            set
            {
                this.clienteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getClienteByIdRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://espe.edu.ec/arquisoft/cliente/ws", Order=0)]
        public CrearCliente.getClienteByIdRequest getClienteByIdRequest;
        
        public getClienteByIdRequest1()
        {
        }
        
        public getClienteByIdRequest1(CrearCliente.getClienteByIdRequest getClienteByIdRequest)
        {
            this.getClienteByIdRequest = getClienteByIdRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getClienteByIdResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://espe.edu.ec/arquisoft/cliente/ws", Order=0)]
        public CrearCliente.getClienteByIdResponse getClienteByIdResponse;
        
        public getClienteByIdResponse1()
        {
        }
        
        public getClienteByIdResponse1(CrearCliente.getClienteByIdResponse getClienteByIdResponse)
        {
            this.getClienteByIdResponse = getClienteByIdResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://espe.edu.ec/arquisoft/cliente/ws")]
    public partial class modificarEstadoClienteBancaWebRequest
    {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://espe.edu.ec/arquisoft/cliente/ws")]
    public partial class modificarEstadoClienteBancaWebResponse
    {
        
        private Cliente clienteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Cliente Cliente
        {
            get
            {
                return this.clienteField;
            }
            set
            {
                this.clienteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modificarEstadoClienteBancaWebRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://espe.edu.ec/arquisoft/cliente/ws", Order=0)]
        public CrearCliente.modificarEstadoClienteBancaWebRequest modificarEstadoClienteBancaWebRequest;
        
        public modificarEstadoClienteBancaWebRequest1()
        {
        }
        
        public modificarEstadoClienteBancaWebRequest1(CrearCliente.modificarEstadoClienteBancaWebRequest modificarEstadoClienteBancaWebRequest)
        {
            this.modificarEstadoClienteBancaWebRequest = modificarEstadoClienteBancaWebRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modificarEstadoClienteBancaWebResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://espe.edu.ec/arquisoft/cliente/ws", Order=0)]
        public CrearCliente.modificarEstadoClienteBancaWebResponse modificarEstadoClienteBancaWebResponse;
        
        public modificarEstadoClienteBancaWebResponse1()
        {
        }
        
        public modificarEstadoClienteBancaWebResponse1(CrearCliente.modificarEstadoClienteBancaWebResponse modificarEstadoClienteBancaWebResponse)
        {
            this.modificarEstadoClienteBancaWebResponse = modificarEstadoClienteBancaWebResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://espe.edu.ec/arquisoft/cliente/ws")]
    public partial class getClienteRequest
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getClienteRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://espe.edu.ec/arquisoft/cliente/ws", Order=0)]
        public CrearCliente.getClienteRequest getClienteRequest;
        
        public getClienteRequest1()
        {
        }
        
        public getClienteRequest1(CrearCliente.getClienteRequest getClienteRequest)
        {
            this.getClienteRequest = getClienteRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getClienteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getClienteResponse", Namespace="http://espe.edu.ec/arquisoft/cliente/ws", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public CrearCliente.Cliente[] getClienteResponse1;
        
        public getClienteResponse()
        {
        }
        
        public getClienteResponse(CrearCliente.Cliente[] getClienteResponse1)
        {
            this.getClienteResponse1 = getClienteResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://espe.edu.ec/arquisoft/cliente/ws")]
    public partial class eliminarClienteRequest
    {
        
        private string tipoIdentificacionField;
        
        private string identificacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string tipoIdentificacion
        {
            get
            {
                return this.tipoIdentificacionField;
            }
            set
            {
                this.tipoIdentificacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string identificacion
        {
            get
            {
                return this.identificacionField;
            }
            set
            {
                this.identificacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://espe.edu.ec/arquisoft/cliente/ws")]
    public partial class eliminarClienteResponse
    {
        
        private Cliente clienteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Cliente Cliente
        {
            get
            {
                return this.clienteField;
            }
            set
            {
                this.clienteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminarClienteRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://espe.edu.ec/arquisoft/cliente/ws", Order=0)]
        public CrearCliente.eliminarClienteRequest eliminarClienteRequest;
        
        public eliminarClienteRequest1()
        {
        }
        
        public eliminarClienteRequest1(CrearCliente.eliminarClienteRequest eliminarClienteRequest)
        {
            this.eliminarClienteRequest = eliminarClienteRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminarClienteResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://espe.edu.ec/arquisoft/cliente/ws", Order=0)]
        public CrearCliente.eliminarClienteResponse eliminarClienteResponse;
        
        public eliminarClienteResponse1()
        {
        }
        
        public eliminarClienteResponse1(CrearCliente.eliminarClienteResponse eliminarClienteResponse)
        {
            this.eliminarClienteResponse = eliminarClienteResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://espe.edu.ec/arquisoft/cliente/ws")]
    public partial class createdClienteReturnIdRequest
    {
        
        private Cliente clienteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Cliente Cliente
        {
            get
            {
                return this.clienteField;
            }
            set
            {
                this.clienteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://espe.edu.ec/arquisoft/cliente/ws")]
    public partial class createdClienteReturnIdResponse
    {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createdClienteReturnIdRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://espe.edu.ec/arquisoft/cliente/ws", Order=0)]
        public CrearCliente.createdClienteReturnIdRequest createdClienteReturnIdRequest;
        
        public createdClienteReturnIdRequest1()
        {
        }
        
        public createdClienteReturnIdRequest1(CrearCliente.createdClienteReturnIdRequest createdClienteReturnIdRequest)
        {
            this.createdClienteReturnIdRequest = createdClienteReturnIdRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createdClienteReturnIdResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://espe.edu.ec/arquisoft/cliente/ws", Order=0)]
        public CrearCliente.createdClienteReturnIdResponse createdClienteReturnIdResponse;
        
        public createdClienteReturnIdResponse1()
        {
        }
        
        public createdClienteReturnIdResponse1(CrearCliente.createdClienteReturnIdResponse createdClienteReturnIdResponse)
        {
            this.createdClienteReturnIdResponse = createdClienteReturnIdResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://espe.edu.ec/arquisoft/cliente/ws")]
    public partial class createdClienteRequest
    {
        
        private Cliente clienteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Cliente Cliente
        {
            get
            {
                return this.clienteField;
            }
            set
            {
                this.clienteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://espe.edu.ec/arquisoft/cliente/ws")]
    public partial class createdClienteResponse
    {
        
        private Cliente clienteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Cliente Cliente
        {
            get
            {
                return this.clienteField;
            }
            set
            {
                this.clienteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createdClienteRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://espe.edu.ec/arquisoft/cliente/ws", Order=0)]
        public CrearCliente.createdClienteRequest createdClienteRequest;
        
        public createdClienteRequest1()
        {
        }
        
        public createdClienteRequest1(CrearCliente.createdClienteRequest createdClienteRequest)
        {
            this.createdClienteRequest = createdClienteRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createdClienteResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://espe.edu.ec/arquisoft/cliente/ws", Order=0)]
        public CrearCliente.createdClienteResponse createdClienteResponse;
        
        public createdClienteResponse1()
        {
        }
        
        public createdClienteResponse1(CrearCliente.createdClienteResponse createdClienteResponse)
        {
            this.createdClienteResponse = createdClienteResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ClientePortChannel : CrearCliente.ClientePort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ClientePortClient : System.ServiceModel.ClientBase<CrearCliente.ClientePort>, CrearCliente.ClientePort
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ClientePortClient() : 
                base(ClientePortClient.GetDefaultBinding(), ClientePortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ClientePortSoap11.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClientePortClient(EndpointConfiguration endpointConfiguration) : 
                base(ClientePortClient.GetBindingForEndpoint(endpointConfiguration), ClientePortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClientePortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ClientePortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClientePortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ClientePortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClientePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CrearCliente.getClienteByIdResponse1 CrearCliente.ClientePort.getClienteById(CrearCliente.getClienteByIdRequest1 request)
        {
            return base.Channel.getClienteById(request);
        }
        
        public CrearCliente.getClienteByIdResponse getClienteById(CrearCliente.getClienteByIdRequest getClienteByIdRequest)
        {
            CrearCliente.getClienteByIdRequest1 inValue = new CrearCliente.getClienteByIdRequest1();
            inValue.getClienteByIdRequest = getClienteByIdRequest;
            CrearCliente.getClienteByIdResponse1 retVal = ((CrearCliente.ClientePort)(this)).getClienteById(inValue);
            return retVal.getClienteByIdResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CrearCliente.getClienteByIdResponse1> CrearCliente.ClientePort.getClienteByIdAsync(CrearCliente.getClienteByIdRequest1 request)
        {
            return base.Channel.getClienteByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrearCliente.getClienteByIdResponse1> getClienteByIdAsync(CrearCliente.getClienteByIdRequest getClienteByIdRequest)
        {
            CrearCliente.getClienteByIdRequest1 inValue = new CrearCliente.getClienteByIdRequest1();
            inValue.getClienteByIdRequest = getClienteByIdRequest;
            return ((CrearCliente.ClientePort)(this)).getClienteByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CrearCliente.modificarEstadoClienteBancaWebResponse1 CrearCliente.ClientePort.modificarEstadoClienteBancaWeb(CrearCliente.modificarEstadoClienteBancaWebRequest1 request)
        {
            return base.Channel.modificarEstadoClienteBancaWeb(request);
        }
        
        public CrearCliente.modificarEstadoClienteBancaWebResponse modificarEstadoClienteBancaWeb(CrearCliente.modificarEstadoClienteBancaWebRequest modificarEstadoClienteBancaWebRequest)
        {
            CrearCliente.modificarEstadoClienteBancaWebRequest1 inValue = new CrearCliente.modificarEstadoClienteBancaWebRequest1();
            inValue.modificarEstadoClienteBancaWebRequest = modificarEstadoClienteBancaWebRequest;
            CrearCliente.modificarEstadoClienteBancaWebResponse1 retVal = ((CrearCliente.ClientePort)(this)).modificarEstadoClienteBancaWeb(inValue);
            return retVal.modificarEstadoClienteBancaWebResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CrearCliente.modificarEstadoClienteBancaWebResponse1> CrearCliente.ClientePort.modificarEstadoClienteBancaWebAsync(CrearCliente.modificarEstadoClienteBancaWebRequest1 request)
        {
            return base.Channel.modificarEstadoClienteBancaWebAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrearCliente.modificarEstadoClienteBancaWebResponse1> modificarEstadoClienteBancaWebAsync(CrearCliente.modificarEstadoClienteBancaWebRequest modificarEstadoClienteBancaWebRequest)
        {
            CrearCliente.modificarEstadoClienteBancaWebRequest1 inValue = new CrearCliente.modificarEstadoClienteBancaWebRequest1();
            inValue.modificarEstadoClienteBancaWebRequest = modificarEstadoClienteBancaWebRequest;
            return ((CrearCliente.ClientePort)(this)).modificarEstadoClienteBancaWebAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CrearCliente.getClienteResponse CrearCliente.ClientePort.getCliente(CrearCliente.getClienteRequest1 request)
        {
            return base.Channel.getCliente(request);
        }
        
        public CrearCliente.Cliente[] getCliente(CrearCliente.getClienteRequest getClienteRequest)
        {
            CrearCliente.getClienteRequest1 inValue = new CrearCliente.getClienteRequest1();
            inValue.getClienteRequest = getClienteRequest;
            CrearCliente.getClienteResponse retVal = ((CrearCliente.ClientePort)(this)).getCliente(inValue);
            return retVal.getClienteResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CrearCliente.getClienteResponse> CrearCliente.ClientePort.getClienteAsync(CrearCliente.getClienteRequest1 request)
        {
            return base.Channel.getClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrearCliente.getClienteResponse> getClienteAsync(CrearCliente.getClienteRequest getClienteRequest)
        {
            CrearCliente.getClienteRequest1 inValue = new CrearCliente.getClienteRequest1();
            inValue.getClienteRequest = getClienteRequest;
            return ((CrearCliente.ClientePort)(this)).getClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CrearCliente.eliminarClienteResponse1 CrearCliente.ClientePort.eliminarCliente(CrearCliente.eliminarClienteRequest1 request)
        {
            return base.Channel.eliminarCliente(request);
        }
        
        public CrearCliente.eliminarClienteResponse eliminarCliente(CrearCliente.eliminarClienteRequest eliminarClienteRequest)
        {
            CrearCliente.eliminarClienteRequest1 inValue = new CrearCliente.eliminarClienteRequest1();
            inValue.eliminarClienteRequest = eliminarClienteRequest;
            CrearCliente.eliminarClienteResponse1 retVal = ((CrearCliente.ClientePort)(this)).eliminarCliente(inValue);
            return retVal.eliminarClienteResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CrearCliente.eliminarClienteResponse1> CrearCliente.ClientePort.eliminarClienteAsync(CrearCliente.eliminarClienteRequest1 request)
        {
            return base.Channel.eliminarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrearCliente.eliminarClienteResponse1> eliminarClienteAsync(CrearCliente.eliminarClienteRequest eliminarClienteRequest)
        {
            CrearCliente.eliminarClienteRequest1 inValue = new CrearCliente.eliminarClienteRequest1();
            inValue.eliminarClienteRequest = eliminarClienteRequest;
            return ((CrearCliente.ClientePort)(this)).eliminarClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CrearCliente.createdClienteReturnIdResponse1 CrearCliente.ClientePort.createdClienteReturnId(CrearCliente.createdClienteReturnIdRequest1 request)
        {
            return base.Channel.createdClienteReturnId(request);
        }
        
        public CrearCliente.createdClienteReturnIdResponse createdClienteReturnId(CrearCliente.createdClienteReturnIdRequest createdClienteReturnIdRequest)
        {
            CrearCliente.createdClienteReturnIdRequest1 inValue = new CrearCliente.createdClienteReturnIdRequest1();
            inValue.createdClienteReturnIdRequest = createdClienteReturnIdRequest;
            CrearCliente.createdClienteReturnIdResponse1 retVal = ((CrearCliente.ClientePort)(this)).createdClienteReturnId(inValue);
            return retVal.createdClienteReturnIdResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CrearCliente.createdClienteReturnIdResponse1> CrearCliente.ClientePort.createdClienteReturnIdAsync(CrearCliente.createdClienteReturnIdRequest1 request)
        {
            return base.Channel.createdClienteReturnIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrearCliente.createdClienteReturnIdResponse1> createdClienteReturnIdAsync(CrearCliente.createdClienteReturnIdRequest createdClienteReturnIdRequest)
        {
            CrearCliente.createdClienteReturnIdRequest1 inValue = new CrearCliente.createdClienteReturnIdRequest1();
            inValue.createdClienteReturnIdRequest = createdClienteReturnIdRequest;
            return ((CrearCliente.ClientePort)(this)).createdClienteReturnIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CrearCliente.createdClienteResponse1 CrearCliente.ClientePort.createdCliente(CrearCliente.createdClienteRequest1 request)
        {
            return base.Channel.createdCliente(request);
        }
        
        public CrearCliente.createdClienteResponse createdCliente(CrearCliente.createdClienteRequest createdClienteRequest)
        {
            CrearCliente.createdClienteRequest1 inValue = new CrearCliente.createdClienteRequest1();
            inValue.createdClienteRequest = createdClienteRequest;
            CrearCliente.createdClienteResponse1 retVal = ((CrearCliente.ClientePort)(this)).createdCliente(inValue);
            return retVal.createdClienteResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CrearCliente.createdClienteResponse1> CrearCliente.ClientePort.createdClienteAsync(CrearCliente.createdClienteRequest1 request)
        {
            return base.Channel.createdClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrearCliente.createdClienteResponse1> createdClienteAsync(CrearCliente.createdClienteRequest createdClienteRequest)
        {
            CrearCliente.createdClienteRequest1 inValue = new CrearCliente.createdClienteRequest1();
            inValue.createdClienteRequest = createdClienteRequest;
            return ((CrearCliente.ClientePort)(this)).createdClienteAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ClientePortSoap11))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ClientePortSoap11))
            {
                return new System.ServiceModel.EndpointAddress("http://34.125.102.171:8300/ws");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ClientePortClient.GetBindingForEndpoint(EndpointConfiguration.ClientePortSoap11);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ClientePortClient.GetEndpointAddress(EndpointConfiguration.ClientePortSoap11);
        }
        
        public enum EndpointConfiguration
        {
            
            ClientePortSoap11,
        }
    }
}
