//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuota
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://espe.edu.ec/arqsoftware/SpringSOAPPrestamoServer/ws", ConfigurationName="Cuota.cuotaPrestamoPort")]
    public interface cuotaPrestamoPort
    {
        
        // CODEGEN: Generating message contract since the operation obtenerPrestamoIdYEstado is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Cuota.obtenerPrestamoIdYEstadoResponse obtenerPrestamoIdYEstado(Cuota.obtenerPrestamoIdYEstadoRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Cuota.obtenerPrestamoIdYEstadoResponse> obtenerPrestamoIdYEstadoAsync(Cuota.obtenerPrestamoIdYEstadoRequest1 request);
        
        // CODEGEN: Generating message contract since the operation obtenerPrestamoId is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Cuota.obtenerPrestamoIdResponse obtenerPrestamoId(Cuota.obtenerPrestamoIdRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Cuota.obtenerPrestamoIdResponse> obtenerPrestamoIdAsync(Cuota.obtenerPrestamoIdRequest1 request);
        
        // CODEGEN: Generating message contract since the operation pagoCuota is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Cuota.pagoCuotaResponse1 pagoCuota(Cuota.pagoCuotaRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Cuota.pagoCuotaResponse1> pagoCuotaAsync(Cuota.pagoCuotaRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://espe.edu.ec/arqsoftware/SpringSOAPPrestamoServer/ws")]
    public partial class obtenerPrestamoIdYEstadoRequest
    {
        
        private int codigoPrestamoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int codigoPrestamo
        {
            get
            {
                return this.codigoPrestamoField;
            }
            set
            {
                this.codigoPrestamoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://espe.edu.ec/arqsoftware/SpringSOAPPrestamoServer/ws")]
    public partial class cuotaPagoRQ
    {
        
        private int codigoField;
        
        private int codigoPrestamoField;
        
        private decimal valorPagoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int codigoPrestamo
        {
            get
            {
                return this.codigoPrestamoField;
            }
            set
            {
                this.codigoPrestamoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal valorPago
        {
            get
            {
                return this.valorPagoField;
            }
            set
            {
                this.valorPagoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://espe.edu.ec/arqsoftware/SpringSOAPPrestamoServer/ws")]
    public partial class cuotaPrestamoRS
    {
        
        private int codigoField;
        
        private int codigoPrestamoField;
        
        private int anioField;
        
        private int mesField;
        
        private decimal cuotaField;
        
        private decimal cuotaInteresField;
        
        private decimal cuotaSeguroField;
        
        private decimal capitalField;
        
        private decimal saldoAnteriorField;
        
        private decimal saldoActualField;
        
        private string estadoField;
        
        private System.DateTime fechaMaxPagoField;
        
        private System.DateTime fechaPagoField;
        
        private decimal valorPagoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int codigoPrestamo
        {
            get
            {
                return this.codigoPrestamoField;
            }
            set
            {
                this.codigoPrestamoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int anio
        {
            get
            {
                return this.anioField;
            }
            set
            {
                this.anioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int mes
        {
            get
            {
                return this.mesField;
            }
            set
            {
                this.mesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal cuota
        {
            get
            {
                return this.cuotaField;
            }
            set
            {
                this.cuotaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal cuotaInteres
        {
            get
            {
                return this.cuotaInteresField;
            }
            set
            {
                this.cuotaInteresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal cuotaSeguro
        {
            get
            {
                return this.cuotaSeguroField;
            }
            set
            {
                this.cuotaSeguroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal capital
        {
            get
            {
                return this.capitalField;
            }
            set
            {
                this.capitalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal saldoAnterior
        {
            get
            {
                return this.saldoAnteriorField;
            }
            set
            {
                this.saldoAnteriorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal saldoActual
        {
            get
            {
                return this.saldoActualField;
            }
            set
            {
                this.saldoActualField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public System.DateTime fechaMaxPago
        {
            get
            {
                return this.fechaMaxPagoField;
            }
            set
            {
                this.fechaMaxPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public System.DateTime fechaPago
        {
            get
            {
                return this.fechaPagoField;
            }
            set
            {
                this.fechaPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public decimal valorPago
        {
            get
            {
                return this.valorPagoField;
            }
            set
            {
                this.valorPagoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerPrestamoIdYEstadoRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://espe.edu.ec/arqsoftware/SpringSOAPPrestamoServer/ws", Order=0)]
        public Cuota.obtenerPrestamoIdYEstadoRequest obtenerPrestamoIdYEstadoRequest;
        
        public obtenerPrestamoIdYEstadoRequest1()
        {
        }
        
        public obtenerPrestamoIdYEstadoRequest1(Cuota.obtenerPrestamoIdYEstadoRequest obtenerPrestamoIdYEstadoRequest)
        {
            this.obtenerPrestamoIdYEstadoRequest = obtenerPrestamoIdYEstadoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerPrestamoIdYEstadoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerPrestamoIdYEstadoResponse", Namespace="http://espe.edu.ec/arqsoftware/SpringSOAPPrestamoServer/ws", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Cuota.cuotaPrestamoRS[] obtenerPrestamoIdYEstadoResponse1;
        
        public obtenerPrestamoIdYEstadoResponse()
        {
        }
        
        public obtenerPrestamoIdYEstadoResponse(Cuota.cuotaPrestamoRS[] obtenerPrestamoIdYEstadoResponse1)
        {
            this.obtenerPrestamoIdYEstadoResponse1 = obtenerPrestamoIdYEstadoResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://espe.edu.ec/arqsoftware/SpringSOAPPrestamoServer/ws")]
    public partial class obtenerPrestamoIdRequest
    {
        
        private int codigoPrestamoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int codigoPrestamo
        {
            get
            {
                return this.codigoPrestamoField;
            }
            set
            {
                this.codigoPrestamoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerPrestamoIdRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://espe.edu.ec/arqsoftware/SpringSOAPPrestamoServer/ws", Order=0)]
        public Cuota.obtenerPrestamoIdRequest obtenerPrestamoIdRequest;
        
        public obtenerPrestamoIdRequest1()
        {
        }
        
        public obtenerPrestamoIdRequest1(Cuota.obtenerPrestamoIdRequest obtenerPrestamoIdRequest)
        {
            this.obtenerPrestamoIdRequest = obtenerPrestamoIdRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerPrestamoIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerPrestamoIdResponse", Namespace="http://espe.edu.ec/arqsoftware/SpringSOAPPrestamoServer/ws", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Cuota.cuotaPrestamoRS[] obtenerPrestamoIdResponse1;
        
        public obtenerPrestamoIdResponse()
        {
        }
        
        public obtenerPrestamoIdResponse(Cuota.cuotaPrestamoRS[] obtenerPrestamoIdResponse1)
        {
            this.obtenerPrestamoIdResponse1 = obtenerPrestamoIdResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://espe.edu.ec/arqsoftware/SpringSOAPPrestamoServer/ws")]
    public partial class pagoCuotaRequest
    {
        
        private cuotaPagoRQ cuotaPagoRQField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public cuotaPagoRQ cuotaPagoRQ
        {
            get
            {
                return this.cuotaPagoRQField;
            }
            set
            {
                this.cuotaPagoRQField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://espe.edu.ec/arqsoftware/SpringSOAPPrestamoServer/ws")]
    public partial class pagoCuotaResponse
    {
        
        private cuotaPrestamoRS cuotaPrestamoRSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public cuotaPrestamoRS cuotaPrestamoRS
        {
            get
            {
                return this.cuotaPrestamoRSField;
            }
            set
            {
                this.cuotaPrestamoRSField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pagoCuotaRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://espe.edu.ec/arqsoftware/SpringSOAPPrestamoServer/ws", Order=0)]
        public Cuota.pagoCuotaRequest pagoCuotaRequest;
        
        public pagoCuotaRequest1()
        {
        }
        
        public pagoCuotaRequest1(Cuota.pagoCuotaRequest pagoCuotaRequest)
        {
            this.pagoCuotaRequest = pagoCuotaRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pagoCuotaResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://espe.edu.ec/arqsoftware/SpringSOAPPrestamoServer/ws", Order=0)]
        public Cuota.pagoCuotaResponse pagoCuotaResponse;
        
        public pagoCuotaResponse1()
        {
        }
        
        public pagoCuotaResponse1(Cuota.pagoCuotaResponse pagoCuotaResponse)
        {
            this.pagoCuotaResponse = pagoCuotaResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface cuotaPrestamoPortChannel : Cuota.cuotaPrestamoPort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class cuotaPrestamoPortClient : System.ServiceModel.ClientBase<Cuota.cuotaPrestamoPort>, Cuota.cuotaPrestamoPort
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public cuotaPrestamoPortClient() : 
                base(cuotaPrestamoPortClient.GetDefaultBinding(), cuotaPrestamoPortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.cuotaPrestamoPortSoap11.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public cuotaPrestamoPortClient(EndpointConfiguration endpointConfiguration) : 
                base(cuotaPrestamoPortClient.GetBindingForEndpoint(endpointConfiguration), cuotaPrestamoPortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public cuotaPrestamoPortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(cuotaPrestamoPortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public cuotaPrestamoPortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(cuotaPrestamoPortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public cuotaPrestamoPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cuota.obtenerPrestamoIdYEstadoResponse Cuota.cuotaPrestamoPort.obtenerPrestamoIdYEstado(Cuota.obtenerPrestamoIdYEstadoRequest1 request)
        {
            return base.Channel.obtenerPrestamoIdYEstado(request);
        }
        
        public Cuota.cuotaPrestamoRS[] obtenerPrestamoIdYEstado(Cuota.obtenerPrestamoIdYEstadoRequest obtenerPrestamoIdYEstadoRequest)
        {
            Cuota.obtenerPrestamoIdYEstadoRequest1 inValue = new Cuota.obtenerPrestamoIdYEstadoRequest1();
            inValue.obtenerPrestamoIdYEstadoRequest = obtenerPrestamoIdYEstadoRequest;
            Cuota.obtenerPrestamoIdYEstadoResponse retVal = ((Cuota.cuotaPrestamoPort)(this)).obtenerPrestamoIdYEstado(inValue);
            return retVal.obtenerPrestamoIdYEstadoResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cuota.obtenerPrestamoIdYEstadoResponse> Cuota.cuotaPrestamoPort.obtenerPrestamoIdYEstadoAsync(Cuota.obtenerPrestamoIdYEstadoRequest1 request)
        {
            return base.Channel.obtenerPrestamoIdYEstadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cuota.obtenerPrestamoIdYEstadoResponse> obtenerPrestamoIdYEstadoAsync(Cuota.obtenerPrestamoIdYEstadoRequest obtenerPrestamoIdYEstadoRequest)
        {
            Cuota.obtenerPrestamoIdYEstadoRequest1 inValue = new Cuota.obtenerPrestamoIdYEstadoRequest1();
            inValue.obtenerPrestamoIdYEstadoRequest = obtenerPrestamoIdYEstadoRequest;
            return ((Cuota.cuotaPrestamoPort)(this)).obtenerPrestamoIdYEstadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cuota.obtenerPrestamoIdResponse Cuota.cuotaPrestamoPort.obtenerPrestamoId(Cuota.obtenerPrestamoIdRequest1 request)
        {
            return base.Channel.obtenerPrestamoId(request);
        }
        
        public Cuota.cuotaPrestamoRS[] obtenerPrestamoId(Cuota.obtenerPrestamoIdRequest obtenerPrestamoIdRequest)
        {
            Cuota.obtenerPrestamoIdRequest1 inValue = new Cuota.obtenerPrestamoIdRequest1();
            inValue.obtenerPrestamoIdRequest = obtenerPrestamoIdRequest;
            Cuota.obtenerPrestamoIdResponse retVal = ((Cuota.cuotaPrestamoPort)(this)).obtenerPrestamoId(inValue);
            return retVal.obtenerPrestamoIdResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cuota.obtenerPrestamoIdResponse> Cuota.cuotaPrestamoPort.obtenerPrestamoIdAsync(Cuota.obtenerPrestamoIdRequest1 request)
        {
            return base.Channel.obtenerPrestamoIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cuota.obtenerPrestamoIdResponse> obtenerPrestamoIdAsync(Cuota.obtenerPrestamoIdRequest obtenerPrestamoIdRequest)
        {
            Cuota.obtenerPrestamoIdRequest1 inValue = new Cuota.obtenerPrestamoIdRequest1();
            inValue.obtenerPrestamoIdRequest = obtenerPrestamoIdRequest;
            return ((Cuota.cuotaPrestamoPort)(this)).obtenerPrestamoIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cuota.pagoCuotaResponse1 Cuota.cuotaPrestamoPort.pagoCuota(Cuota.pagoCuotaRequest1 request)
        {
            return base.Channel.pagoCuota(request);
        }
        
        public Cuota.pagoCuotaResponse pagoCuota(Cuota.pagoCuotaRequest pagoCuotaRequest)
        {
            Cuota.pagoCuotaRequest1 inValue = new Cuota.pagoCuotaRequest1();
            inValue.pagoCuotaRequest = pagoCuotaRequest;
            Cuota.pagoCuotaResponse1 retVal = ((Cuota.cuotaPrestamoPort)(this)).pagoCuota(inValue);
            return retVal.pagoCuotaResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cuota.pagoCuotaResponse1> Cuota.cuotaPrestamoPort.pagoCuotaAsync(Cuota.pagoCuotaRequest1 request)
        {
            return base.Channel.pagoCuotaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cuota.pagoCuotaResponse1> pagoCuotaAsync(Cuota.pagoCuotaRequest pagoCuotaRequest)
        {
            Cuota.pagoCuotaRequest1 inValue = new Cuota.pagoCuotaRequest1();
            inValue.pagoCuotaRequest = pagoCuotaRequest;
            return ((Cuota.cuotaPrestamoPort)(this)).pagoCuotaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.cuotaPrestamoPortSoap11))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.cuotaPrestamoPortSoap11))
            {
                return new System.ServiceModel.EndpointAddress("http://34.125.102.171:8000/ws");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return cuotaPrestamoPortClient.GetBindingForEndpoint(EndpointConfiguration.cuotaPrestamoPortSoap11);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return cuotaPrestamoPortClient.GetEndpointAddress(EndpointConfiguration.cuotaPrestamoPortSoap11);
        }
        
        public enum EndpointConfiguration
        {
            
            cuotaPrestamoPortSoap11,
        }
    }
}
