//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.28 at 08:03:50 PM ECT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://espe.edu.ec/arqsoftware/prestamo/zamora_zuniga/ws", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ec.edu.espe.arqsoftware.prestamo.bridge.soap;
